import("//build_overrides/build.gni")
import("//build_overrides/chip.gni")
import("//build_overrides/pigweed.gni")
import("${chip_root}/build/chip/chip_test_suite.gni")

chip_test_suite("tests") {
  output_name = "TestMicrowaveOvenControlCluster"

  test_sources = [
    "TestMicrowaveOvenControlE2E.cpp",
    "TestMicrowaveOvenControlSpecGap.cpp",
  ]

  sources = [
    # Production cluster servers under test
    "../microwave-oven-control-server.cpp",
    "${chip_root}/src/app/clusters/operational-state-server/operational-state-server.cpp",
    "${chip_root}/src/app/clusters/mode-base-server/mode-base-server.cpp",
    "${chip_root}/src/app/clusters/mode-base-server/mode-base-cluster-objects.cpp",

    # Test stubs
    "MicrowaveOvenControlTestStubs.cpp",
  ]

  cflags = [ "-Wconversion" ]

  public_deps = [
    "${chip_root}/src/app",
    "${chip_root}/src/app:attribute-persistence",
    "${chip_root}/src/app/common:cluster-objects",
    "${chip_root}/src/app/util/mock:mock_ember",
    "${chip_root}/src/lib/core",
    "${chip_root}/src/lib/support",
  ]
}
