import("//build_overrides/build.gni")
import("//build_overrides/chip.gni")
import("//build_overrides/pigweed.gni")
import("${chip_root}/build/chip/chip_test_suite.gni")

chip_test_suite("tests") {
  output_name = "TestEnergyEvseCluster"

  test_sources = [
    "TestEnergyEvseE2E.cpp",
    "TestEnergyEvseSpecGap.cpp",
  ]

  sources = [
    # Production cluster server under test
    "../energy-evse-server.cpp",

    # Test stubs
    "EnergyEvseTestStubs.cpp",
  ]

  cflags = [ "-Wconversion" ]

  public_deps = [
    "${chip_root}/src/app",
    "${chip_root}/src/app:attribute-persistence",
    "${chip_root}/src/app/common:cluster-objects",
    "${chip_root}/src/app/util/mock:mock_ember",
    "${chip_root}/src/lib/core",
    "${chip_root}/src/lib/support",
  ]
}
